oTree/vickrey_auction/models.py
from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)
import random


doc = """
In this Vickrey auction, 3 players bid for an object with private values. Each
player can only submit one bid.

See: Vickrey, William. "Counterspeculation, auctions, and competitive '
sealed tenders." The Journal of finance 16.1 (1961): 8-37.
"""


class Constants(BaseConstants):
    name_in_url = 'vickrey_auction'
    players_per_group = 3
    num_rounds = 1

    instructions_template = 'vickrey_auction/Instructions.html'

    endowment = c(100)


class Subsession(BaseSubsession):
    def before_session_starts(self):
        for p in self.get_players():
            p.private_value = random.randint(0, Constants.endowment)


class Group(BaseGroup):
    highest_bid = models.CurrencyField()
    second_highest_bid = models.CurrencyField()

    def set_highest_bids(self):
        bids = sorted((p.bid_amount for p in self.get_players()), reverse=True)
        self.highest_bid = bids[0]
        self.second_highest_bid = bids[1]

    def set_payoffs(self):
        self.set_highest_bids()
        players_with_highest_bid = [
            p for p in self.get_players()
            if p.bid_amount == self.highest_bid
            ]
        # if tie, winner is chosen at random
        winner = random.choice(players_with_highest_bid)
        winner.is_winner = True
        for p in self.get_players():
            p.payoff = Constants.endowment
            if p.is_winner:
                p.payoff += (p.private_value - self.second_highest_bid)



class Player(BasePlayer):
    private_value = models.CurrencyField(
        doc="How much the player values the item, generated randomly"
    )

    bid_amount = models.CurrencyField(
        min=0, max=Constants.endowment,
        doc="Amount bidded by the player"
    )

    is_winner = models.BooleanField(
        initial=False,
        doc="""Indicates whether the player is the winner"""
    )

oTree/vickrey_auction/_builtin/__init__.py
# Don't change anything in this file.
from .. import models
import otree.api

import otree.api
from otree.api import Currency as c, currency_range

class Page(otree.api.Page):

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()


class WaitPage(otree.api.WaitPage):


    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()


class Bot(otree.api.Bot):

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()

oTree/vickrey_auction/views.py
from . import models
from ._builtin import Page, WaitPage
from otree.api import Currency as c, currency_range
from .models import Constants


class Introduction(Page):
    pass


class Bid(Page):
    form_model = models.Player
    form_fields = ['bid_amount']


class ResultsWaitPage(WaitPage):
    def after_all_players_arrive(self):
        self.group.set_payoffs()


class Results(Page):
    pass


page_sequence = [
    Introduction,
    Bid,
    ResultsWaitPage,
    Results]

oTree/vickrey_auction/templates/vickrey_auction/Bid.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Bid
{% endblock %}

{% block styles %}
<link href="{% static "vickrey_auction/jquery-ui/jquery-ui.min.css" %}" rel="stylesheet">
<style type="text/css">
    .bid-slider {
        margin: 1.5em auto;
        width: 70%;
    }

    .bid {
        text-align: center;
    }

    .payoff {
        margin: 1.5em 0;
    }
</style>
{% endblock %}

{% block scripts %}
<script src="{% static "vickrey_auction/jquery-ui/jquery-ui.min.js" %}"></script>
<script>
jQuery(document).ready(function ($) {
    var PRIVATE_VALUE = {{ player.private_value.to_number|escapejs }};

    var input = $('#id_bid_amount');

    $('.bid-slider').slider({
        min: 0,
        max: 100,
        slide: function (event, ui) {
            input.val(ui.value);
            updateBidValue();
        },
    });

    function updateBidValue() {
        $('.bid-value').text(input.val());
        $('.payoff-value').text(calculatePayoff());
    }

    function calculatePayoff() {
        var value = parseInt(input.val());
        var payoff = 100 + PRIVATE_VALUE;
        return payoff;
    }

    updateBidValue();
});
</script>
{% endblock %}

{% block content %}

    <p>
        Your value to the object is <strong>{{ player.private_value }}</strong>.
    </p>

    <div class="form-group required">
        <label class="control-label" for="id_bid_amount">Please submit a bid for the object (from 0 to 100):</label>
        <div class="controls">
            <input type="hidden" name="bid_amount" id="id_bid_amount" value="0">
            <div class="bid-slider"></div>
            <div class="bid">Your bid: <strong><span class="bid-value"></span> points</strong></div>
            <div class="payoff">If you win the auction, you would have a payoff of <strong><span class="payoff-value"></span> points - Second highest bid</strong>.</div>
        </div>
    </div>

    {% next_button %}

    {% include Constants.instructions_template %}

{% endblock %}

oTree/vickrey_auction/templates/vickrey_auction/Instructions.html
{% load otree_tags staticfiles %}

<div class="instructions well well-lg">

    <h3 class="panel-sub-heading">
        Instructions
    </h3>

    <p>
        You have been randomly and anonymously matched with another 2
        participants in an auction. Each of you is given 100 points to start.
    </p>
    <p>
        Before bidding, you will learn the value of the object to you. The
        value of the object differs from participant to participant and is
        randomly and independently drawn from 0 to 100 for each participant.
    </p>
    <p>
        At auction, you will privately submit one bid for the object. A bid
        can be anything from 0 to 100 points. The participant with the highest
        bid wins the object and pays the second highest bid. A random device
        will select the winner in the event of a tie bid and the winner will
        pay the highest bid other than her or his own bid.
    </p>
    <p>
        The payoff of the winner is calculated as (in points)<br/>
        <strong>
            Winner’s payoff = 100 + Private value of the object to the winner - Second highest bid
        </strong><br/>
        The payoffs for others are the initial 100 points.
    </p>
    <p>
        For your convenience, these instructions will remain available to you on all subsequent screens of this study.
    </p>

</div>

oTree/vickrey_auction/templates/vickrey_auction/Introduction.html
{% extends "global/Base.html" %}{% load staticfiles otree_tags %}{% block title %}    Introduction{% endblock %}{% block content %}    {% include Constants.instructions_template %}    {% next_button %}{% endblock %}

oTree/vickrey_auction/templates/vickrey_auction/Results.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Results
{% endblock %}

{% block content %}


    <p>
        {% if player.is_winner %}
            You won the auction!
        {% else %}
            You did not win the auction!
        {% endif %}
    </p>

    <table class="table">
        <tr>
            <th>Your value</th>
            <th>Your bid</th>
            <th>Winning bid</th>
            <th>Second-Highest Bid</th>
            <th>You Paid</th>
            <th>Your payoff</th>
        </tr>

        <tr>
            <td>{{ player.private_value }}</td>
            <td>{{ player.bid_amount }}</td>
            <td>{{ group.highest_bid }}</td>
            <td>{{ group.second_highest_bid }}</td>
            <td>
                {% if player.is_winner %}
                    {{ group.second_highest_bid }}
                {% else %}
                    0
                {% endif %}
            </td>
            <td>{{ player.payoff|floatformat:"-2" }}</td>
        </tr>

    </table>

    {% next_button %}

    {% include Constants.instructions_template %}

{% endblock %}